### PR TITLE
Customizable ethers provider

### PR DESCRIPTION
**Pull request by ghost**
Give user an ability to inject alternative ethers.js compatible providers ( Infura, Etherscan, Alchemy, IPC, Web3.js wrapped one, etc )

cc @dan1kov

### CODE REVIEW

**Comment by Pasha8914** [comment]
@ayanamidev is it necessary to validate the provided provider for compatibility ?

For example, if I provide a web3.js provider then txManager crashed

**Comment by ghost** [comment]
@Pasha8914 If it crashes it is likely a bug from ethers.js and you should create an issue

https://docs.ethers.io/v5/api/providers/other/#Web3Provider

Documentation says that any operations should be compatible.

**Comment by Pasha8914** [comment]
> @Pasha8914 If it crashes it is likely a bug from ethers.js and you should create an issue
> 
> https://docs.ethers.io/v5/api/providers/other/#Web3Provider
> 
> Documentation says that any operations should be compatible.

can you develop a test using some of the popular providers

**Comment by ghost** [comment]
@Pasha8914 No problem, will generate the test case that matches with the use of tx-manager

https://github.com/ethers-io/ethers.js/discussions/1758

This could might be helpful

**Review by poma — APPROVED** [review]

**Comment by poma** [comment]
I think we should check that it's an instance of `JsonRpcProvider` or maybe `BaseProvider` (not sure if it implements all the calls required for tx-manager)

**Comment by poma** [comment]
also `provider` overrides `rpcUrl`, so maybe it should be a single argument that is used depending on its type (directly if it inherits `JsonRpcProvider`, via constructor if it's a string, error otherwise). Renaming it would be a breaking change though, so major version should be incremented in this case.

**Comment by ghost** [comment]
@poma I will port Tx Manager to Typescript with advanced Error handling features. I am recently developing Web3 / Ethers.js compatible JsonRpcProvider called [web3-providers-axios](https://github.com/ayanamitech/web3-providers-axios) to address connection issues on Tor network, However I think we need deeper Error handling & some improved type checks to make it work for any hostile network environment ( like when the infura node gone dark, etc ).

**Review by dan1kov — APPROVED** [review]

**Pull request merged**
